import { useCallback, useEffect, useMemo, useState } from "react";
import toast from "react-hot-toast";
import { getAvatarUrl } from "../utils/url";
import "../css/AuditManagement.css";

const CATEGORY_META = {
  administrativo: { label: "Administrativo", icon: "bi-person", tone: "green" },
  chat: { label: "Chat", icon: "bi-chat-square-dots", tone: "purple" },
  chat_grupal: { label: "Chat grupal", icon: "bi-people", tone: "orange" },
  seguridad: { label: "Seguridad", icon: "bi-shield-lock", tone: "blue" },
  blacklist: { label: "Blacklist", icon: "bi-ban", tone: "red" },
};

const fmtDate = (value) => {
  if (!value) return "—";
  const d = new Date(String(value).replace(" ", "T") + (String(value).includes("Z") ? "" : "Z"));
  if (Number.isNaN(d.getTime())) return value;
  return d.toLocaleString("es-PE", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", second: "2-digit" });
};

const initials = (row) => `${row?.actor_nombre?.[0] || row?.actor_correo?.[0] || "S"}`.toUpperCase();
const displayActor = (row) => `${row?.actor_nombre || ""} ${row?.actor_apellido || ""}`.trim() || row?.actor_correo || "Sistema";
const displayTarget = (row) => `${row?.objetivo_nombre || ""} ${row?.objetivo_apellido || ""}`.trim() || row?.objetivo_correo || row?.metadata?.body?.nombre || "—";

function StatCard({ icon, value, label, tone, sub }) {
  return <article className={`qa-stat qa-${tone}`}><span className="qa-stat-icon"><i className={`bi ${icon}`} /></span><div><strong>{Number(value || 0).toLocaleString("es-PE")}</strong><b>{label}</b>{sub && <small>{sub}</small>}</div><span className="qa-spark"><i /><i /></span></article>;
}

function CategoryPill({ active, onClick, icon, children, tone = "blue" }) {
  return <button type="button" className={`qa-category ${active ? "active" : ""} qa-${tone}`} onClick={onClick}><i className={`bi ${icon}`} />{children}</button>;
}

function Pagination({ page, total, limit, onPage }) {
  const pages = Math.max(1, Math.ceil(total / limit));
  return <div className="qa-pagination"><span>Mostrando {total ? (page - 1) * limit + 1 : 0} a {Math.min(page * limit, total)} de {total}</span><div><button disabled={page <= 1} onClick={() => onPage(page - 1)}>‹</button><strong>{page}</strong><button disabled={page >= pages} onClick={() => onPage(page + 1)}>›</button></div></div>;
}

function AuditDetail({ id, onBack }) {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    let active = true;
    setLoading(true);
    fetch(`/api/registros/${id}`, { credentials: "include" })
      .then(async r => { const j = await r.json().catch(() => ({})); if (!r.ok) throw new Error(j.error || "No se pudo cargar el registro"); return j; })
      .then(j => active && setData(j)).catch(e => active && toast.error(e.message)).finally(() => active && setLoading(false));
    return () => { active = false; };
  }, [id]);
  if (loading) return <div className="qa-loading"><span className="spinner-border" /> Cargando detalle…</div>;
  if (!data?.record) return <div className="qa-empty">No se encontró el registro.</div>;
  const r = data.record;
  const meta = CATEGORY_META[r.categoria] || CATEGORY_META.administrativo;
  const beforeText = r.valores_anteriores?.texto ?? r.valores_anteriores?.mensaje ?? null;
  const afterText = r.valores_nuevos?.texto ?? r.valores_nuevos?.mensaje ?? null;
  return <main className="qa-page qa-detail-page">
    <div className="qa-bg"><span className="qa-orb qa-orb-one"/><span className="qa-orb qa-orb-two"/><span className="qa-decor-line qa-decor-line-one"/><span className="qa-decor-line qa-decor-line-two"/><i className="bi bi-chat-dots qa-floating-icon qa-floating-chat"/><i className="bi bi-file-earmark-text qa-floating-icon qa-floating-file"/></div>
    <header className="qa-page-top qa-detail-top"><button className="qa-outline-btn" onClick={onBack}><i className="bi bi-arrow-left" /> Volver a historial</button><div className="qa-title-block"><h1>Detalle del registro</h1><p>Revisa la evidencia, el contexto y los cambios del evento seleccionado.</p></div><div className="qa-top-actions">{data.context?.length > 0 && <button className="qa-outline-btn" onClick={() => document.getElementById("qa-context-section")?.scrollIntoView({ behavior: "smooth", block: "center" })}><i className="bi bi-chat-square-dots" /> Ver contexto del chat</button>}<button className="qa-gradient-btn" onClick={() => window.open(`/api/registros/export.csv?q=${encodeURIComponent(r.evento || "")}`, "_blank")}><i className="bi bi-download" /> Exportar</button></div></header>
    <section className="qa-detail-shell">
      <div className="qa-detail-head"><span className={`qa-event-chip qa-${meta.tone}`}><i className={`bi ${meta.icon}`} /> {meta.label}</span><div><h2>{r.accion}</h2><p>{r.evento.replaceAll("_", " ").toLowerCase()}</p></div><span className={`qa-status ${r.resultado}`}>{r.resultado === "exitoso" ? "Exitoso" : r.resultado === "alerta" ? "Alerta" : "Fallido"}</span></div>
      <div className="qa-detail-facts">
        <div><i className="bi bi-person"/><span><small>Actor</small><strong>{displayActor(r)}</strong><em>{r.actor_correo || "—"}</em></span></div>
        <div><i className="bi bi-people"/><span><small>Objetivo</small><strong>{displayTarget(r)}</strong><em>{r.objetivo_correo || "—"}</em></span></div>
        <div><i className="bi bi-layers"/><span><small>Proyecto</small><strong>{r.proyecto_nombre || "Sin proyecto"}</strong></span></div>
        <div><i className="bi bi-calendar3"/><span><small>Fecha y hora</small><strong>{fmtDate(r.creado_en)}</strong></span></div>
        <div><i className="bi bi-globe2"/><span><small>IP</small><strong>{r.ip || "No disponible"}</strong></span></div>
        <div><i className="bi bi-display"/><span><small>Dispositivo</small><strong>{r.dispositivo || "No disponible"}</strong></span></div>
        <div><i className="bi bi-key"/><span><small>Permiso utilizado</small><strong>{r.permiso_utilizado || "No aplica"}</strong></span></div>
        <div><i className="bi bi-file-earmark-text"/><span><small>ID relacionado</small><strong>{r.mensaje_id ? `MSG-${r.mensaje_id}` : r.grupo_id ? `GRP-${r.grupo_id}` : `REG-${r.id}`}</strong></span></div>
      </div>
      {(beforeText != null || afterText != null || r.valores_anteriores || r.valores_nuevos) && <section className="qa-change-card"><h3><i className="bi bi-pencil"/> Cambios del evento <small>Compara la información anterior y la nueva.</small></h3><div className="qa-change-grid"><div className="qa-before"><b><i className="bi bi-file-earmark-text"/> Valor anterior</b><pre>{beforeText ?? JSON.stringify(r.valores_anteriores || {}, null, 2)}</pre></div><span className="qa-change-arrow"><i className="bi bi-arrow-right"/></span><div className="qa-after"><b><i className="bi bi-file-earmark-text"/> Valor nuevo</b><pre>{afterText ?? JSON.stringify(r.valores_nuevos || {}, null, 2)}</pre></div></div></section>}
      <div className="qa-detail-bottom">
        <section id="qa-context-section" className="qa-context-card"><h3><i className="bi bi-chat-square-dots"/> Contexto del chat <small>Vista previa alrededor del evento.</small></h3>{data.context?.length ? <div className="qa-context-list">{data.context.map(m => <div key={m.id} className={`qa-context-msg ${Number(m.id) === Number(r.mensaje_id) ? "focus" : ""}`}>{m.url_imagen?<span className="qa-avatar qa-avatar-image"><img src={getAvatarUrl(m.url_imagen)} alt={`${m.nombre || ""} ${m.apellido || ""}`.trim() || "Usuario"} /></span>:<span className="qa-avatar">{(m.nombre?.[0] || "U").toUpperCase()}</span>}<div><strong>{`${m.nombre || ""} ${m.apellido || ""}`.trim() || `Usuario ${m.usuario_id || m.usuario_envia_id}`}</strong><p>{m.eliminado ? "Mensaje eliminado" : m.mensaje}</p></div><time>{fmtDate(m.fecha_envio)}</time></div>)}</div> : <p className="qa-muted">Este tipo de registro no tiene contexto de chat asociado.</p>}</section>
        <section className="qa-trail-card"><h3><i className="bi bi-clock-history"/> Traza del evento <small>Acciones relacionadas.</small></h3><div className="qa-trail">{(data.trail?.length ? data.trail : [{ id:r.id,evento:r.evento,accion:r.accion,creado_en:r.creado_en }]).map((t,i)=><div key={t.id}><span className={i===1?"purple":""}/><div><strong>{t.accion}</strong><p>{String(t.evento||"").replaceAll("_"," ")}</p></div><time>{fmtDate(t.creado_en)}</time></div>)}</div></section>
      </div>
    </section>
  </main>;
}

function RuleModal({ open, rule, projects, onClose, onSaved }) {
  const blank = { palabra:"",categoria:"seguridad",severidad:"alta",aplicar_chats:true,aplicar_grupos:true,aplicar_administrativos:false,proyecto_id:"",coincidencia:"exacta",accion:"registrar",activa:true,observacion:"" };
  const [form,setForm]=useState(blank); const [saving,setSaving]=useState(false);
  useEffect(()=>{ if(open) setForm(rule ? { ...blank, ...rule, proyecto_id: rule.proyecto_id || "", aplicar_chats:Boolean(rule.aplicar_chats),aplicar_grupos:Boolean(rule.aplicar_grupos),aplicar_administrativos:Boolean(rule.aplicar_administrativos),activa:Boolean(rule.activa)} : blank); },[open,rule]);
  if(!open)return null;
  const toggleApply=(key)=>setForm(v=>({...v,[key]:!v[key]}));
  const save=async()=>{setSaving(true);try{const url=rule?`/api/registros/blacklist/rules/${rule.id}`:"/api/registros/blacklist/rules";const res=await fetch(url,{method:rule?"PUT":"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,proyecto_id:form.proyecto_id?Number(form.proyecto_id):null})});const j=await res.json().catch(()=>({}));if(!res.ok)throw new Error(j.error||"No se pudo guardar");toast.success(rule?"Regla actualizada":"Palabra añadida");onSaved();onClose();}catch(e){toast.error(e.message);}finally{setSaving(false);}};
  return <div className="qa-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="qa-rule-modal"><header><span className="qa-modal-icon"><i className="bi bi-plus-circle"/></span><div><h2>{rule?"Editar palabra de blacklist":"Añadir palabra a blacklist"}</h2><p>Configura una palabra o frase para detectar en chats y grupos.</p></div><button onClick={onClose}><i className="bi bi-x-lg"/></button></header><div className="qa-rule-grid"><div className="qa-rule-form">
    <label>1. Palabra o frase *</label><input value={form.palabra} onChange={e=>setForm(v=>({...v,palabra:e.target.value}))} placeholder="Ej.: hack, spam, estafa" />
    <label>2. Categoría *</label><div className="qa-choice-row">{[["seguridad","Seguridad"],["spam","Spam"],["fraude","Fraude"],["acoso","Acoso"],["contenido_sensible","Contenido sensible"],["personalizada","Personalizada"]].map(([v,l])=><button className={form.categoria===v?"selected":""} onClick={()=>setForm(f=>({...f,categoria:v}))} key={v}>{l}</button>)}</div>
    <label>3. Severidad *</label><div className="qa-choice-row qa-severity">{["baja","media","alta","critica"].map(v=><button className={`${v} ${form.severidad===v?"selected":""}`} onClick={()=>setForm(f=>({...f,severidad:v}))} key={v}>{v[0].toUpperCase()+v.slice(1)}</button>)}</div>
    <label>4. Aplicar en *</label><div className="qa-choice-row"><button className={form.aplicar_chats?"selected":""} onClick={()=>toggleApply("aplicar_chats")}>Chats</button><button className={form.aplicar_grupos?"selected":""} onClick={()=>toggleApply("aplicar_grupos")}>Chats grupales</button><button className={form.aplicar_administrativos?"selected":""} onClick={()=>toggleApply("aplicar_administrativos")}>Administrativos</button></div>
    <label>5. Proyecto *</label><select value={form.proyecto_id} onChange={e=>setForm(v=>({...v,proyecto_id:e.target.value}))}><option value="">Todos los proyectos</option>{projects.map(p=><option value={p.id} key={p.id}>{p.nombre}</option>)}</select>
    <label>6. Coincidencia *</label><div className="qa-choice-row">{[["exacta","Exacta"],["contiene","Contiene"],["variaciones","Variaciones"]].map(([v,l])=><button className={form.coincidencia===v?"selected":""} onClick={()=>setForm(f=>({...f,coincidencia:v}))} key={v}>{l}</button>)}</div>
    <label>7. Acción al detectar *</label><div className="qa-choice-row">{[["registrar","Solo registrar"],["alerta","Generar alerta"],["notificar","Notificar administradores"]].map(([v,l])=><button className={form.accion===v?"selected":""} onClick={()=>setForm(f=>({...f,accion:v}))} key={v}>{l}</button>)}</div>
    <label className="qa-toggle-line">8. Activa <button className={`qa-switch ${form.activa?"on":""}`} onClick={()=>setForm(f=>({...f,activa:!f.activa}))}><span/></button><small>La palabra estará activa inmediatamente al guardarla.</small></label>
    <label>9. Observación interna</label><textarea maxLength={300} value={form.observacion||""} onChange={e=>setForm(v=>({...v,observacion:e.target.value}))} placeholder="Ej.: motivo de la regla, contexto, notas para el equipo…"/><small className="qa-counter">{(form.observacion||"").length}/300</small>
  </div><aside className="qa-preview"><h3><i className="bi bi-eye"/> Vista previa</h3><p>Así funcionará esta regla de detección:</p><dl><dt>Palabra o frase</dt><dd>{form.palabra||"—"}</dd><dt>Categoría</dt><dd>{form.categoria}</dd><dt>Severidad</dt><dd>{form.severidad}</dd><dt>Aplicar en</dt><dd>{[form.aplicar_chats&&"Chats",form.aplicar_grupos&&"Chats grupales",form.aplicar_administrativos&&"Administrativos"].filter(Boolean).join(", ")||"—"}</dd><dt>Proyecto</dt><dd>{projects.find(p=>String(p.id)===String(form.proyecto_id))?.nombre||"Todos los proyectos"}</dd><dt>Coincidencia</dt><dd>{form.coincidencia}</dd><dt>Acción</dt><dd>{form.accion}</dd><dt>Estado</dt><dd>{form.activa?"Activa":"Inactiva"}</dd></dl><div className="qa-preview-note"><i className="bi bi-info-circle"/> Las coincidencias se registran para auditoría. La blacklist no elimina mensajes automáticamente.</div><h4>Ejemplo de detección</h4><div className="qa-example"><span>J</span><p>Juan Pérez<br/>voy a <mark>{form.palabra||"hack"}</mark> el sistema luego</p></div></aside></div><footer><button className="qa-outline-btn" onClick={onClose}>Cancelar</button><button className="qa-gradient-btn" disabled={saving||!form.palabra.trim()} onClick={save}><i className="bi bi-floppy"/> {saving?"Guardando…":"Guardar palabra"}</button></footer></section></div>;
}


function BlacklistRulesModal({ open, rules, canManage, onClose, onEdit, onDelete }) {
  if (!open) return null;
  return <div className="qa-modal-backdrop qa-list-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}>
    <section className="qa-rules-modal">
      <header>
        <span className="qa-modal-icon"><i className="bi bi-list-ul"/></span>
        <div><h2>Lista de Palabras</h2><p>Consulta y administra las palabras o frases añadidas a la blacklist.</p></div>
        <button type="button" className="qa-icon-close" onClick={onClose} aria-label="Cerrar"><i className="bi bi-x-lg"/></button>
      </header>
      <div className="qa-rules-table-wrap">
        <table className="qa-rules-table">
          <thead><tr><th>Palabra o frase</th><th>Categoría</th><th>Severidad</th><th>Proyecto</th><th>Estado</th><th>Añadida por</th><th>Fecha y hora</th>{canManage&&<th className="qa-rules-actions-head">Acciones</th>}</tr></thead>
          <tbody>{rules?.length ? rules.map(rule=>{
            const creator=`${rule.creado_por_nombre||''} ${rule.creado_por_apellido||''}`.trim()||rule.creado_por_correo||'Sistema';
            return <tr key={rule.id}>
              <td><div className="qa-rule-word"><span className="qa-rule-word-icon"><i className="bi bi-shield-exclamation"/></span><div><b>{rule.palabra}</b><small>{rule.coincidencia==='exacta'?'Coincidencia exacta':rule.coincidencia==='contiene'?'Contiene texto':'Variaciones'}</small></div></div></td>
              <td><span className="qa-rule-category">{String(rule.categoria||'personalizada').replace('_',' ')}</span></td>
              <td><span className={`qa-sev ${rule.severidad}`}>{rule.severidad}</span></td>
              <td>{rule.proyecto_nombre||'Todos los proyectos'}</td>
              <td><span className={`qa-rule-state ${rule.activa?'active':'inactive'}`}><i/> {rule.activa?'Activa':'Inactiva'}</span></td>
              <td><div className="qa-rule-creator">{rule.creado_por_imagen?<span className="qa-avatar qa-avatar-image"><img src={getAvatarUrl(rule.creado_por_imagen)} alt={creator} /></span>:<span className="qa-avatar">{(rule.creado_por_nombre?.[0]||rule.creado_por_correo?.[0]||'S').toUpperCase()}</span>}<div><b>{creator}</b><small>{rule.creado_por_correo||'—'}</small></div></div></td>
              <td>{fmtDate(rule.creado_en)}</td>
              {canManage&&<td className="qa-rules-actions-cell"><div className="qa-rule-actions"><button type="button" className="edit" title="Editar palabra" onClick={()=>onEdit(rule)}><i className="bi bi-pencil"/></button><button type="button" className="delete" title="Eliminar palabra" onClick={()=>onDelete(rule)}><i className="bi bi-trash3"/></button></div></td>}
            </tr>;
          }) : <tr><td colSpan={canManage?8:7}><div className="qa-rules-empty"><i className="bi bi-list-ul"/><b>No hay palabras añadidas</b><span>Usa “Añadir palabra” para crear la primera regla de blacklist.</span></div></td></tr>}</tbody>
        </table>
      </div>
      <footer><span>{rules?.length||0} {(rules?.length||0)===1?'palabra registrada':'palabras registradas'}</span><button type="button" className="qa-outline-btn" onClick={onClose}>Cerrar</button></footer>
    </section>
  </div>;
}

function BlacklistView({ perms, onBack }) {
  const [stats,setStats]=useState({}); const [rules,setRules]=useState([]); const [filtersData,setFiltersData]=useState({projects:[],users:[]});
  const [data,setData]=useState({rows:[],total:0,page:1,limit:25}); const [filters,setFilters]=useState({q:"",tipo:"",proyecto_id:"",usuario_id:"",palabra:"",desde:"",hasta:"",severidad:"",estado:""});
  const [selected,setSelected]=useState(null); const [modal,setModal]=useState(false); const [rulesOpen,setRulesOpen]=useState(false); const [editing,setEditing]=useState(null); const canManage=perms.has("gestionar_blacklist"); const canExport=perms.has("exportar_registros");
  const query=useMemo(()=>{const p=new URLSearchParams({page:String(data.page||1),limit:"25"});Object.entries(filters).forEach(([k,v])=>v&&p.set(k,v));return p.toString();},[filters,data.page]);
  const load=useCallback(async()=>{try{const [s,r,f,d]=await Promise.all([fetch('/api/registros/blacklist/stats',{credentials:'include'}),fetch('/api/registros/blacklist/rules',{credentials:'include'}),fetch('/api/registros/filters',{credentials:'include'}),fetch(`/api/registros/blacklist?${query}`,{credentials:'include'})]);const [sj,rj,fj,dj]=await Promise.all([s.json(),r.json(),f.json(),d.json()]);if(!s.ok||!r.ok||!d.ok)throw new Error(sj.error||rj.error||dj.error||'No se pudo cargar blacklist');setStats(sj);setRules(rj);setFiltersData(fj);setData(prev=>({...prev,...dj}));setSelected(prev=>prev?dj.rows?.find(x=>Number(x.id)===Number(prev.id))||prev:dj.rows?.[0]||null);}catch(e){toast.error(e.message);}},[query]);
  useEffect(()=>{load();},[load]);
  const setF=(k,v)=>{setData(d=>({...d,page:1}));setFilters(f=>({...f,[k]:v}));};
  const removeRule=async(rule)=>{if(!confirm(`¿Eliminar la regla "${rule.palabra}"?`))return;const r=await fetch(`/api/registros/blacklist/rules/${rule.id}`,{method:'DELETE',credentials:'include'});const j=await r.json().catch(()=>({}));if(!r.ok)return toast.error(j.error||'No se pudo eliminar');toast.success('Regla eliminada');load();};
  return <main className="qa-page qa-blacklist-page"><div className="qa-bg"><span className="qa-orb qa-orb-one"/><span className="qa-orb qa-orb-two"/><span className="qa-decor-line qa-decor-line-one"/><span className="qa-decor-line qa-decor-line-two"/><i className="bi bi-chat-dots qa-floating-icon qa-floating-chat"/><i className="bi bi-file-earmark-text qa-floating-icon qa-floating-file"/></div><header className="qa-page-top"><div className="qa-title-block"><button className="qa-link-back" onClick={onBack}><i className="bi bi-arrow-left"/> Registros</button><h1>Registros de blacklist</h1><p>Monitorea palabras restringidas detectadas en chats y grupos.</p></div><div className="qa-top-actions">{canManage&&<button className="qa-outline-btn" onClick={()=>setRulesOpen(true)}><i className="bi bi-list-ul"/> Lista de Palabras</button>}{canManage&&<button className="qa-gradient-btn" onClick={()=>{setEditing(null);setModal(true)}}><i className="bi bi-plus-circle"/> Añadir palabra</button>}{canExport&&<button className="qa-gradient-btn" onClick={()=>window.open(`/api/registros/blacklist/export.csv?${query}`,'_blank')}><i className="bi bi-download"/> Exportar</button>}</div></header>
    <section className="qa-black-shell"><div className="qa-black-stats"><StatCard icon="bi-file-earmark-text" value={stats.reglas} label="Palabras monitorizadas" sub="Reglas activas" tone="blue"/><StatCard icon="bi-chat-square-dots" value={stats.coincidencias} label="Coincidencias" sub="Detecciones registradas" tone="green"/><StatCard icon="bi-people" value={stats.usuarios} label="Usuarios detectados" sub="Usuarios únicos" tone="purple"/><StatCard icon="bi-exclamation-triangle" value={stats.criticas} label="Alertas críticas" sub="Severidad crítica" tone="red"/></div>
    <div className={`qa-black-layout ${selected?"has-detail":""}`}><div className="qa-black-main"><div className="qa-categories"><CategoryPill active={!filters.tipo&&!filters.severidad} onClick={()=>{setF('tipo','');setF('severidad','')}} icon="bi-grid" tone="blue">Todas ({data.total||0})</CategoryPill><CategoryPill active={filters.tipo==='chat'} onClick={()=>setF('tipo','chat')} icon="bi-chat-square-dots" tone="purple">Chats</CategoryPill><CategoryPill active={filters.tipo==='grupo'} onClick={()=>setF('tipo','grupo')} icon="bi-people" tone="orange">Chats grupales</CategoryPill><CategoryPill active={filters.tipo==='administrativo'} onClick={()=>setF('tipo','administrativo')} icon="bi-person" tone="green">Administrativos</CategoryPill><CategoryPill active={filters.severidad==='critica'} onClick={()=>setF('severidad','critica')} icon="bi-exclamation-triangle" tone="red">Críticas</CategoryPill></div>
    <div className="qa-black-filter-shell"><div className="qa-black-filter-row qa-black-filter-row-primary"><label className="qa-search"><i className="bi bi-search"/><input placeholder="Buscar en registros…" value={filters.q} onChange={e=>setF('q',e.target.value)}/></label><select value={filters.proyecto_id} onChange={e=>setF('proyecto_id',e.target.value)}><option value="">Proyecto · Todos</option>{filtersData.projects?.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select><select value={filters.usuario_id} onChange={e=>setF('usuario_id',e.target.value)}><option value="">Usuario · Todos</option>{filtersData.users?.map(u=><option key={u.id} value={u.id}>{u.nombre} {u.apellido}</option>)}</select><select value={filters.palabra} onChange={e=>setF('palabra',e.target.value)}><option value="">Palabra · Todas</option>{rules.map(r=><option key={r.id}>{r.palabra}</option>)}</select></div><div className="qa-black-filter-row qa-black-filter-row-secondary"><label className="qa-date-field"><span>Fecha de inicio</span><input type="date" value={filters.desde} onChange={e=>setF('desde',e.target.value)}/></label><label className="qa-date-field"><span>Fecha de fin</span><input type="date" value={filters.hasta} onChange={e=>setF('hasta',e.target.value)}/></label><select value={filters.severidad} onChange={e=>setF('severidad',e.target.value)}><option value="">Severidad · Todas</option><option value="baja">Baja</option><option value="media">Media</option><option value="alta">Alta</option><option value="critica">Crítica</option></select><select value={filters.estado} onChange={e=>setF('estado',e.target.value)}><option value="">Estado · Todos</option><option value="registrado">Registrado</option><option value="alerta">Alerta</option><option value="revisado">Revisado</option><option value="resuelto">Resuelto</option></select></div></div>
    <div className="qa-table-wrap"><table><thead><tr><th>Fecha y hora</th><th>Usuario</th><th>Categoría</th><th>Palabra detectada</th><th>Coincidencia / frase</th><th>Proyecto</th><th>Severidad</th><th>Estado</th><th>Detalle</th></tr></thead><tbody>{data.rows?.map(row=><tr key={row.id} className={selected?.id===row.id?'selected':''}><td>{fmtDate(row.creado_en)}</td><td><div className="qa-user-cell">{row.actor_imagen?<span className="qa-avatar qa-avatar-image"><img src={getAvatarUrl(row.actor_imagen)} alt={`${row.actor_nombre||''} ${row.actor_apellido||''}`.trim()||'Usuario'} /></span>:<span className="qa-avatar">{(row.actor_nombre?.[0]||'U').toUpperCase()}</span>}<div><b>{`${row.actor_nombre||''} ${row.actor_apellido||''}`.trim()||'Usuario'}</b><small>{row.actor_correo}</small></div></div></td><td><span className={`qa-chip qa-${row.tipo==='grupo'?'orange':row.tipo==='chat'?'purple':'green'}`}>{row.tipo==='grupo'?'Chat grupal':row.tipo==='chat'?'Chat':'Administrativo'}</span></td><td><b>{row.palabra_detectada}</b></td><td className="qa-snippet">{row.coincidencia_texto}</td><td>{row.proyecto_nombre||'—'}</td><td><span className={`qa-sev ${row.severidad}`}>{row.severidad}</span></td><td><span className={`qa-status ${row.estado==='alerta'?'alerta':'exitoso'}`}>{row.estado}</span></td><td><button className="qa-mini-btn" onClick={()=>setSelected(row)}><i className="bi bi-eye"/> Ver detalle</button></td></tr>)}</tbody></table><Pagination page={data.page||1} total={data.total||0} limit={data.limit||25} onPage={p=>setData(d=>({...d,page:p}))}/></div></div>
    {selected&&<aside className="qa-detection-panel"><header><h3>Detalle de detección</h3><button onClick={()=>setSelected(null)}>×</button></header><dl><dt>Palabra detectada</dt><dd><span className="qa-sev critica">{selected.palabra_detectada}</span></dd><dt>Actor</dt><dd>{`${selected.actor_nombre||''} ${selected.actor_apellido||''}`.trim()||selected.actor_correo}</dd><dt>Objetivo</dt><dd>{`${selected.objetivo_nombre||''} ${selected.objetivo_apellido||''}`.trim()||selected.objetivo_correo||'—'}</dd><dt>Proyecto</dt><dd>{selected.proyecto_nombre||'—'}</dd><dt>Fecha y hora</dt><dd>{fmtDate(selected.creado_en)}</dd><dt>Tipo de chat</dt><dd>{selected.tipo}</dd><dt>Coincidencia</dt><dd>{selected.coincidencia_texto}</dd><dt>Contexto del mensaje</dt><dd className="qa-context-box">{selected.contexto}</dd><dt>Acción tomada</dt><dd><span className="qa-status alerta">{selected.accion_tomada}</span></dd></dl>{canManage&&<div className="qa-detection-actions"><button onClick={async()=>{await fetch(`/api/registros/blacklist/${selected.id}/status`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({estado:'revisado'})});load();}}>Marcar revisado</button><button onClick={async()=>{await fetch(`/api/registros/blacklist/${selected.id}/status`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({estado:'resuelto'})});load();}}>Resolver</button></div>}</aside>}</div></section><BlacklistRulesModal open={rulesOpen} rules={rules} canManage={canManage} onClose={()=>setRulesOpen(false)} onEdit={(rule)=>{setRulesOpen(false);setEditing(rule);setModal(true)}} onDelete={removeRule}/><RuleModal open={modal} rule={editing} projects={filtersData.projects||[]} onClose={()=>setModal(false)} onSaved={load}/></main>;
}

export default function AuditManagement({ usuarioLogueado }) {
  const perms=useMemo(()=>new Set(usuarioLogueado?.rol_permisos||[]),[usuarioLogueado]);
  const [view,setView]=useState('history'); const [detailId,setDetailId]=useState(null); const [stats,setStats]=useState({}); const [filtersData,setFiltersData]=useState({projects:[],users:[],actions:[]});
  const [filters,setFilters]=useState({q:"",categoria:"",proyecto_id:"",usuario_id:"",accion:"",desde:"",hasta:"",resultado:""}); const [data,setData]=useState({rows:[],total:0,page:1,limit:25}); const [loading,setLoading]=useState(true);
  const canBlacklist=perms.has('ver_blacklist')||perms.has('gestionar_blacklist')||perms.has('ver_registros'); const canExport=perms.has('exportar_registros');
  const query=useMemo(()=>{const p=new URLSearchParams({page:String(data.page||1),limit:"25"});Object.entries(filters).forEach(([k,v])=>v&&p.set(k,v));return p.toString();},[filters,data.page]);
  const load=useCallback(async()=>{setLoading(true);try{const [s,f,l]=await Promise.all([fetch('/api/registros/stats',{credentials:'include'}),fetch('/api/registros/filters',{credentials:'include'}),fetch(`/api/registros?${query}`,{credentials:'include'})]);const [sj,fj,lj]=await Promise.all([s.json(),f.json(),l.json()]);if(!s.ok||!l.ok)throw new Error(sj.error||lj.error||'No se pudieron cargar los registros');setStats(sj);setFiltersData(fj);setData(d=>({...d,...lj}));}catch(e){toast.error(e.message);}finally{setLoading(false);}},[query]);
  useEffect(()=>{if(view==='history')load();},[view,load]);
  const setF=(k,v)=>{setData(d=>({...d,page:1}));setFilters(f=>({...f,[k]:v}));};
  if(view==='detail'&&detailId)return <AuditDetail id={detailId} onBack={()=>setView('history')}/>;
  if(view==='blacklist')return <BlacklistView perms={perms} onBack={()=>setView('history')}/>;
  const categoryTotal={administrativo:stats.administrativos,chat:stats.chats,chat_grupal:stats.chats_grupales,seguridad:stats.seguridad,blacklist:stats.alertas};
  return <main className="qa-page"><div className="qa-bg"><span className="qa-orb qa-orb-one"/><span className="qa-orb qa-orb-two"/><span className="qa-decor-line qa-decor-line-one"/><span className="qa-decor-line qa-decor-line-two"/><i className="bi bi-chat-dots qa-floating-icon qa-floating-chat"/><i className="bi bi-file-earmark-text qa-floating-icon qa-floating-file"/></div><header className="qa-page-top"><div className="qa-title-block"><h1>Registros</h1><p>Monitorea y audita la actividad administrativa y de chat de tu organización.</p></div><div className="qa-top-actions">{canBlacklist&&<button className="qa-outline-btn" onClick={()=>setView('blacklist')}><i className="bi bi-shield-exclamation"/> Palabras Blacklist</button>}{canExport&&<button className="qa-gradient-btn" onClick={()=>window.open(`/api/registros/export.csv?${query}`,'_blank')}><i className="bi bi-download"/> Exportar</button>}</div></header>
    <section className="qa-history-shell"><div className="qa-history-hero"><span className="qa-hero-icon"><i className="bi bi-file-earmark-text"/></span><div><h2>Historial de registros</h2><p>Consulta los eventos administrativos, de chat y de seguridad de tu organización.</p></div></div>
      <div className="qa-stats-row"><StatCard icon="bi-file-earmark-text" value={stats.total} label="Registros totales" sub="En total" tone="blue"/><StatCard icon="bi-people" value={stats.administrativos} label="Administrativos" sub="De gestión del sistema" tone="green"/><StatCard icon="bi-chat-square-dots" value={stats.chats} label="Chats" sub="De conversaciones" tone="purple"/><StatCard icon="bi-people" value={stats.chats_grupales} label="Chats grupales" sub="De grupos de chat" tone="orange"/><StatCard icon="bi-exclamation-triangle" value={stats.alertas} label="Alertas" sub="Eventos de seguridad" tone="red"/></div>
      <div className="qa-categories"><CategoryPill active={!filters.categoria} onClick={()=>setF('categoria','')} icon="bi-grid" tone="blue">Todos</CategoryPill>{Object.entries(CATEGORY_META).map(([k,m])=><CategoryPill key={k} active={filters.categoria===k} onClick={()=>setF('categoria',k)} icon={m.icon} tone={m.tone}>{m.label}{categoryTotal[k]!=null?` (${categoryTotal[k]})`:''}</CategoryPill>)}</div>
      <div className="qa-filter-grid"><label className="qa-search"><i className="bi bi-search"/><input value={filters.q} onChange={e=>setF('q',e.target.value)} placeholder="Buscar en registros…"/></label><select value={filters.proyecto_id} onChange={e=>setF('proyecto_id',e.target.value)}><option value="">Proyecto · Todos</option>{filtersData.projects?.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select><select value={filters.usuario_id} onChange={e=>setF('usuario_id',e.target.value)}><option value="">Usuario · Todos</option>{filtersData.users?.map(u=><option key={u.id} value={u.id}>{u.nombre} {u.apellido}</option>)}</select><select value={filters.accion} onChange={e=>setF('accion',e.target.value)}><option value="">Acción · Todas</option>{filtersData.actions?.map(a=><option key={a.evento} value={a.evento}>{a.accion}</option>)}</select><input type="date" value={filters.desde} onChange={e=>setF('desde',e.target.value)}/><input type="date" value={filters.hasta} onChange={e=>setF('hasta',e.target.value)}/><select value={filters.resultado} onChange={e=>setF('resultado',e.target.value)}><option value="">Resultado · Todos</option><option value="exitoso">Exitoso</option><option value="alerta">Alerta</option><option value="fallido">Fallido</option></select></div>
      <div className="qa-table-wrap history"><table><thead><tr><th>Fecha y hora</th><th>Usuario</th><th>Categoría</th><th>Acción</th><th>Objetivo</th><th>Proyecto</th><th>Estado</th><th>Detalle</th></tr></thead><tbody>{loading?<tr><td colSpan="8"><div className="qa-loading"><span className="spinner-border spinner-border-sm"/> Cargando registros…</div></td></tr>:data.rows?.length?data.rows.map(row=>{const m=CATEGORY_META[row.categoria]||CATEGORY_META.administrativo;return <tr key={row.id}><td>{fmtDate(row.creado_en)}</td><td><div className="qa-user-cell">{row.actor_imagen?<span className="qa-avatar qa-avatar-image"><img src={getAvatarUrl(row.actor_imagen)} alt={displayActor(row)} /></span>:<span className="qa-avatar">{initials(row)}</span>}<div><b>{displayActor(row)}</b><small>{row.actor_correo||'—'}</small></div></div></td><td><span className={`qa-chip qa-${m.tone}`}><i className={`bi ${m.icon}`}/> {m.label}</span></td><td><b className="qa-action-name">{row.accion}</b></td><td>{displayTarget(row)}</td><td><span className="qa-project-chip"><i className="bi bi-layers"/> {row.proyecto_nombre||'—'}</span></td><td><span className={`qa-status ${row.resultado}`}>{row.resultado}</span></td><td><button className="qa-mini-btn" onClick={()=>{setDetailId(row.id);setView('detail')}}><i className="bi bi-eye"/> Ver detalle</button></td></tr>}):<tr><td colSpan="8"><div className="qa-empty">No hay registros para los filtros seleccionados.</div></td></tr>}</tbody></table><Pagination page={data.page||1} total={data.total||0} limit={data.limit||25} onPage={p=>setData(d=>({...d,page:p}))}/></div>
      <div className="qa-info-strip"><i className="bi bi-info-circle"/> Este módulo centraliza registros administrativos, chats, grupos, seguridad y blacklist, con filtros y aislamiento por proyecto.</div>
    </section>
  </main>;
}
